name: 'Compile AutoHotkey'
description: 'Compile AutoHotkey scripts using Ahk2Exe.'
author: 'benmusson'
branding:
  color: 'blue'
  icon: 'command'

inputs:
  in:
    required: true
    description: 'The path and name of the script to compile.'

  out:
    required: false
    description: >
      The path\name of the output .exe to be created. 
      Default is the directory\base_name of the input file plus extension of .exe, 
      or any relevant compiler directive in the script.

  icon:
    required: false
    description: >
      The icon file to be used. 
      Default is any SetMainIcon compiler directive in the script.

  target:
    required: false
    description: 'Target architecture. Valid options: x86, x64. Defaults to x64.'
    default: 'x64'

  resourceid:
    required: false
    description: >
      Assigns a non-standard resource ID to be used for the main script for
      compilations which use an .exe base file (see Embedded Scripts). 
      Numeric resource IDs should consist of a hash sign (#) followed by a 
      decimal number. 
      Default is #1, or any ResourceID compiler directive in the script.

  compression:
    required: false
    description: >
      Specifies which compression method to use. Valid options: none, upx. Defaults to upx.
    default: 'upx'

  ahk-repo:
    required: false
    description: 'GitHub repository source for AutoHotkey.'
    default: 'AutoHotkey/AutoHotkey'

  ahk-tag:
    required: false
    description: 'Tagged GitHub release for AutoHotkey.'
    default: 'latest'

  ahk2exe-repo:
    required: false
    description: 'GitHub repository source for Ahk2Exe.'
    default: 'AutoHotkey/Ahk2Exe'

  ahk2exe-tag:
    required: false
    description: 'Tagged GitHub release for Ahk2Exe.'
    default: 'latest'

  upx-repo:
    required: false
    description: 'GitHub repository source for UPX.'
    default: 'UPX/UPX'

  upx-tag:
    required: false
    description: 'Tagged GitHub release for UPX.'
    default: 'latest'

  build-assets-folder:
    required: false
    description: 'The path used to store build assets downloaded during the action.'
    default: '.\.ahk2exe-v2-action'
  github-token:
    description: Set to use token for GitHub authentication (avoids rate limiting).
    required: false

runs:
  using: composite
  steps:
    - name: Build
      shell: pwsh
      run: ${{ github.action_path }}\action.ps1
      env:
        GitHubToken: ${{ inputs.github-token }}
        In: "${{ inputs.in }}"
        Out: "${{ inputs.out }}"
        Icon: "${{ inputs.icon }}"
        Target: "${{ inputs.target }}"
        ResourceId: "${{ inputs.resourceid }}"
        Compression: "${{ inputs.compression }}"

        AutoHotkeyRepo: "${{ inputs.ahk-repo }}"
        AutoHotkeyTag: "${{ inputs.ahk-tag }}"
        Ahk2ExeRepo: "${{ inputs.ahk2exe-repo }}"
        Ahk2ExeTag: "${{ inputs.ahk2exe-tag }}"
        UPXRepo: "${{ inputs.upx-repo }}"
        UPXTag: "${{ inputs.upx-tag }}"

        BuildAssetsFolder: "${{ inputs.build-assets-folder }}"
