name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test x64 Target
        uses: ./
        continue-on-error: true
        with:
          in: .\testing\v2.0\test.ahk
          out: .\output\test_x64.exe
          icon: .\testing\icons\test.ico
          compression: upx
          target: x64

      - name: Test x86 Target
        uses: ./
        continue-on-error: true
        with:
          in: .\testing\v2.0\test.ahk
          out: .\output\test_x86.exe
          icon: .\testing\icons\test.ico
          compression: upx
          target: x86

      - name: Test No Compression
        uses: ./
        continue-on-error: true
        with:
          in: .\testing\v2.0\test.ahk
          out: .\output\text_x64_uncompressed.exe
          icon: .\testing\icons\test.ico
          compression: none

      - name: Test No Icon
        uses: ./
        continue-on-error: true
        with:
          in: .\testing\v2.0\test.ahk
          out: .\output\test_no_icon.exe
          target: x64

      - name: Test Default Output
        uses: ./
        continue-on-error: true
        with:
          in: .\test\scripts\test.ahk2
          target: x64

      - name: Test ResourceId
        uses: ./
        continue-on-error: true
        with:
          in: .\test\scripts\test.ahk2
          out: .\output\test_resourceid.exe
          target: x64
          resourceid: 5

      - name: Check for Failed Test
        run: |
          if(
            ![System.IO.File]::Exists('.\output\test_x64.exe') ||
            ![System.IO.File]::Exists('.\output\test_x86.exe') ||
            ![System.IO.File]::Exists('.\output\text_x64_uncompressed.exe') ||
            ![System.IO.File]::Exists('.\output\test_no_icon.exe') ||
            ![System.IO.File]::Exists('.\output\test.exe') ||
            ![System.IO.File]::Exists('.\output\test_resourceid.exe')
          ) {
            throw "Tests Failed"  
          } else {
            Write-Output "All Tests Passed!" 
          }
